version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./:/var/www/html/
    depends_on:
      - php
      - mysql

  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/var/www/html/
    depends_on:
      - mysql
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_twitter
      MYSQL_DATABASE: twitter
      MYSQL_USER: twitter
      MYSQL_PASSWORD: twitter
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
  php-worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: php worker.php
    depends_on:
      - php
    volumes:
      - .:/var/www/html